baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 15
googleAnalytics = "UA-128511835-2"
enableEmoji=true
[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true


  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
 #updatedDatePrefix = "Updated: 2020-xx-xx"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""
[markup]
 [markup.goldmark.renderer]
 	unsafe=true
[languages]
  [languages.en]
    languageName = "English"
    title = "Nikhil Raghav's Blog"
    subtitle = ""
    owner = "Nikhil Raghav"
    keywords = ""
    copyright = "Â© Nikhil Raghav 2021"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "nikhil1_raghav"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
	[[languages.en.menu.main]]
	identifier="archive"
	name="Archive"
	url="/archive"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
	[[languages.en.menu.main]]
	identifier="links"
	name="Links"
	url="/links"
	[[languages.en.menu.main]]
	identifier="Books"
	name="Books"
	url="/books"
	[[languages.en.menu.main]]
	identifier="TIL"
	name="TIL"
	url="/til"
